### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by Sense** [mxrch/GitFive#3] opened 2022-10-10 07:30 UTC
I'm facing an issue with Python 3.10.4 while running Gitfive locally.

```
[XRAY] 🎭 Impersonating users got in dumped commits...
[METAMON] 🐙 Added commits in 0.66s !

[+] [Target's email] 🐱 XYZ@gmail.com -> @XYZ
[+] Deleted the remote repo
Traceback (most recent call last):
  File "/Users/jvq/.local/bin/gitfive", line 8, in <module>
    sys.exit(main())
  File "/Users/jvq/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/gitfive.py", line 14, in main
    parse_args()
  File "/Users/jvq/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/cli.py", line 51, in parse_args
    trio.run(username_mod.hunt, args.username, args.json)
  File "/Users/jvq/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/Users/jvq/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/modules/username_mod.py", line 157, in hunt
    await xray.analyze(runner)
  File "/Users/jvq/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/xray.py", line 253, in analyze
    await github.delete_repo(runner, temp_repo_name)
  File "/Users/jvq/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/github.py", line 38, in delete_repo
    authenticity_token = [x for x in form.find_all('input') if "name" in x.attrs and x.attrs["name"] == "authenticity_token"][0].attrs["value"]

AttributeError: 'NoneType' object has no attribute 'find_all'

```

**Comment by mxrch** [comment] 2022-10-10 08:14
Hi, I can't reproduce this issue. Does this happens everytime with multiple targets ?
It looks like it doesn't find the form to delete the repo, there should be no reason for it to happens.

**Comment by Sreegs** [comment] 2022-10-13 23:24
Hi! I'm having this same issue. It doesn't matter what account I run it against. I just tried running it against mine then yours for instance and received the same error. Running in python 3.10.4 on macos.

**Comment by mxrch** [comment] 2022-11-20 22:24
Hi, I can reproduce this bug now, that's when we identify the spoofed users, GitFive gets the hovercard of the user to get his full name, GitHub has a little rate-limit (429 status code on the screenshot).
I'll maybe lower the requests speed at this moment, or optimize the calls.

![image](https://user-images.githubusercontent.com/17338428/202929569-c81d9db3-73fa-4869-bc8e-9339e8769ac7.png)

**Comment by mxrch** [comment] 2022-11-23 17:20
Fixed in https://github.com/mxrch/GitFive/releases/tag/v1.1.0 !

**Closed by mxrch** 2022-11-23 17:20 UTC
Labels: bug
